### ISSUE TITLE
Support sign hex string

### ISSUE THREAD

**Issue by xuxiaohu** [RubyCrypto/ed25519#26]
When the message is hex string like(0x0b00586cb27c291c813ce74e86a60dad270609abf2fc8bee107e44a80ac00225c409070010a5d4e80028000100000001000000d9bdd928bef54b08037a91aef4d051e5f6aacdd2cceb839ce58b668e275a161fd9bdd928bef54b08037a91aef4d051e5f6aacdd2cceb839ce58b668e275a161f),
 When i use sign message, give me a wrong message.which is different from python result and js result. 
please support it

**Comment by tarcieri** [comment]
These crates don't natively implement any sort of encoding support and only operate on bytestrings.

If you'd like to sign binary data encoded in hex, please use something like the [`hex` crate](https://crates.io/crates/hex) to decode it first.
