### ISSUE TITLE
Release new version for jRuby 9.3 support

### ISSUE THREAD

**Issue by jboler** [RubyCrypto/ed25519#34]
Hi! I see you have a fix committed to fix jRuby 9.3 - could you release a new gem version with the fix?

I'm getting this error with capistrano and your fix seems to work when I paste it in manually:
```
NoMethodError: undefined method `runtime' for JRuby:Module
```

Thanks!

**Comment by jboler** [comment]
@tarcieri - are you able to publish a new gem release for the jRuby 9.3 fix? Thanks!

**Comment by tarcieri** [comment]
Sorry, will try to look at this soon

**Comment by tarcieri** [comment]
Released in #35
