### ISSUE TITLE
public and secret key

### ISSUE THREAD

**Issue by og1en** [RubyCrypto/ed25519#41]
How expoert public and secret key
for example I need send public key to friend

for example https://ssbc.github.io/scuttlebutt-protocol-guide/#discovery

**Comment by tarcieri** [comment]
See https://github.com/RubyCrypto/ed25519?tab=readme-ov-file#serializing-keys

**Comment by og1en** [comment]
I m not see example:

skey = Ed25519::SigningKey.generate

I have a key. Question is how extracting public key for send my friend and how extract private key?

**Comment by tarcieri** [comment]
See "Obtain the verify key for a given signing key" above here: https://github.com/RubyCrypto/ed25519?tab=readme-ov-file#usage

**Comment by og1en** [comment]
skey = Ed25519::SigningKey.generate

is contains 2 keys similar in RSA? 

What You mean about verify key ? I need pub key.

**Comment by tarcieri** [comment]
The verify key is the public key

**Comment by og1en** [comment]
and from verify key I cant generate secret key?

**Comment by tarcieri** [comment]
No, that would defeat the purpose of public key cryptography

**Comment by og1en** [comment]
ok, tell me how export public and private key to blob, openssl txt format, raw data?

```
p signing_key.verify_key
<Ed25519::VerifyKey:e5add6988fd8e8eb27e99822a9da0d0a92e36095e90cb32a375529b88d5ea288>
```

**to_s** not working
any idea?

**Comment by tarcieri** [comment]
[I already covered that above](https://github.com/RubyCrypto/ed25519/issues/41#issuecomment-1974864026).

Please actually read the documentation.

**Comment by og1en** [comment]
It is compatibility with openssl ?
I can generate commandline ssl and use it in ruby and vice versa?
